# Generated by Django 4.1.7 on 2023-03-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_dic', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_dic', models.CharField(max_length=100)),
                ('product_price', models.PositiveBigIntegerField()),
                ('product_Image', models.URLField(blank=True, null=True)),
                ('product_category', models.ManyToManyField(related_name='category', to='product.category')),
            ],
        ),
    ]
