# Generated by Django 4.1.7 on 2023-03-07 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_address_street_remove_address_zip_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='user_profile.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
