# Generated by Django 4.1.7 on 2023-03-17 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_profile_signup_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='signup_id',
            new_name='signup_profile',
        ),
    ]
